[settings]
lockfile = true
lockfile_platforms = ["linux-x64"]

[tool_alias]
cagent = "github:u7chan/code-agent-launcher"

[tools]
node = "lts"
bun = "1"
uv = "latest"
ripgrep = "latest"
fd = "latest"
neovim = "0.12"
yazi = "latest"
starship = "latest"
herdr = "latest"
cagent = { version = "0.1.1", filter_bins = "cagent" }
