[settings]
lockfile = true
lockfile_platforms = ["linux-x64"]
minimum_release_age = "1h"

[tool_alias]
cagent = "github:u7chan/code-agent-launcher"

[tools]
node = "lts"
bun = "1"
uv = "latest"
ripgrep = "latest"
fd = "latest"
tree-sitter = "latest"
neovim = "0.12"
hunk = "latest"
lazygit = "latest"
lazydocker = "latest"
yazi = "latest"
starship = "latest"
herdr = "latest"
zoxide = "latest"
fzf = "latest"
cagent = { version = "0.1.2", filter_bins = "cagent" }
